name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Format, Lint, Test: ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [1.18 1.20 1.21, 1.22, 1.23, 1.24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-go-

      - name: Check formatting with gofmt
        run: |
          fmt_count=$(gofmt -l . | wc -l)
          if [ "$fmt_count" -ne 0 ]; then
            echo "The following files are not properly formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test -coverprofile=coverage.out -v ./...