name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Format, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # or your desired version

      - name: Check formatting with gofmt
        run: |
          fmt_count=$(gofmt -l . | wc -l)
          if [ "$fmt_count" -ne 0 ]; then
            echo "The following files are not properly formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2  # choose latest stable version

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test -v ./...