name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [1.21, 1.22, 1.23, 1.24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          
      - name: Verify Go version
        run: go version          

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          key: cache-os-${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test -coverprofile=coverage.out -v ./...